

public enum PatientMenu
{
    START_MENU,
    EXAM_MENU,
    PROCEDURES_MENU,
    TRIAGE_MENU,
    OPEN_AIRWAYS_MENU,
    TALK_MENU,
    MEASURE_PULSE_AND_BREATHING_MENU,
    CAN_YOU_WALK_RESPONSE,
    WHERE_DOES_IT_HURT_RESPONSE,
    BREATHING_RESPONSE,
    BLEEDING_RESPONSE,
    COUNT_BREATHING_RESPONSE,
    WRIST_PULSE_RESPONSE,
    NECK_PULSE_RESPONSE,
}
